# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: count.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63ount.proto\x12\x05\x63ount\"\x0e\n\x0c\x43ountRequest\"\x1e\n\rCountResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x32\x46\n\x0c\x43ountService\x12\x36\n\tIncrement\x12\x13.count.CountRequest\x1a\x14.count.CountResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'count_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_COUNTREQUEST']._serialized_start=22
  _globals['_COUNTREQUEST']._serialized_end=36
  _globals['_COUNTRESPONSE']._serialized_start=38
  _globals['_COUNTRESPONSE']._serialized_end=68
  _globals['_COUNTSERVICE']._serialized_start=70
  _globals['_COUNTSERVICE']._serialized_end=140
# @@protoc_insertion_point(module_scope)
